
exports.seed = function(knex, Promise) {
  return Promise.join(
    // Deletes ALL existing entries
    knex('beer').del(),

    // Inserts seed entries
    knex('beer').insert({name:'Cara', style: 'Irish Pale Ale', brewer:'Rahmona Henry & James Griffiths', yield:60, brewDate:'03 Jan 2016', bottlingDate:'01 Mar 2016', original: 1071, final: 1014, mash: 60, ferment: 18, abv: 7, ibu: 45, ingredients: 'Golden Promise Malt,Caramalt,Carapils Malt,Cascade Hops,Chinook Hops', brewing:'Add malts to 9L of H20 at 74 °C. Mash for 60 minutes. Recirculate. Sparging. Collect 23 L of wort. Boil, add hops for 60 minutes.Cool wort, aerate, pitch yeast, ferment at 21 °C.', fermentation: 'Ferment started after 24 hours and lasted for 8 days.', tasting:'easy drinking, hint of caramels, and the Cascade hops provides plenty of floral citrus aromas and flavours.'}),
    knex('beer').insert({name:'Pragmatic Chaos', style: 'American IPA', brewer:'Rahmona Henry', yield:72, brewDate:'01 Dec 2015', bottlingDate:'30 Dec 2015', original: 1078, final: 1020, mash: 64, ferment: 20, abv: 6, ibu: 58, ingredients: 'Pale Malt, Biscuit Malt, Munich Malt, Chinook Hops, Centennial Hops', brewing: 'Add malts to 9L of H20 at 74 °C. Mash for 60 minutes. Recirculate. Sparging. Collect 23 L of wort. Boil, add hops for 60 minutes.Cool wort, aerate, pitch yeast, ferment at 21 °C.', fermentation: 'Ferment started after 12 hours and lasted for 4 days.', tasting: 'Balanced hop bitterness with a strong malt backbone, floral hop aroma and a finish that is bitter without being harsh or astringent.'}),
    knex('beer').insert({name:'The Duke', style: 'Cask Conditioned Irish Stout', brewer:'Rahmona Henry', yield:72, brewDate:'01 Dec 2015', bottlingDate:'30 Dec 2015', original: 1078, final: 1020, mash: 64, ferment: 20, abv: 6, ibu: 58, ingredients: 'Pale Malt, Biscuit Malt, Munich Malt, Chinook Hops, Centennial Hops', brewing: 'Add malts to 9L of H20 at 74 °C. Mash for 60 minutes. Recirculate. Sparging. Collect 23 L of wort. Boil, add hops for 60 minutes.Cool wort, aerate, pitch yeast, ferment at 21 °C.', fermentation: 'Ferment started after 12 hours and lasted for 4 days.', tasting: 'Balanced hop bitterness with a strong malt backbone, floral hop aroma and a finish that is bitter without being harsh or astringent.'}),
    knex('beer').insert({name:'The Duchess', style: 'Pilsner', brewer:'Rahmona Henry', yield:72, brewDate:'01 Dec 2015', bottlingDate:'30 Dec 2015', original: 1078, final: 1020, mash: 64, ferment: 20, abv: 6, ibu: 58, ingredients: 'Pale Malt, Biscuit Malt, Munich Malt, Chinook Hops, Centennial Hops', brewing: 'Add malts to 9L of H20 at 74 °C. Mash for 60 minutes. Recirculate. Sparging. Collect 23 L of wort. Boil, add hops for 60 minutes.Cool wort, aerate, pitch yeast, ferment at 21 °C.', fermentation: 'Ferment started after 12 hours and lasted for 4 days.', tasting: 'Balanced hop bitterness with a strong malt backbone, floral hop aroma and a finish that is bitter without being harsh or astringent.'}),
    knex('beer').insert({name:'Ted', style: 'IPA', brewer:'Rahmona Henry', yield:72, brewDate:'01 Dec 2015', bottlingDate:'30 Dec 2015', original: 1078, final: 1020, mash: 64, ferment: 20, abv: 6, ibu: 58, ingredients: 'Pale Malt, Biscuit Malt, Munich Malt, Chinook Hops, Centennial Hops', brewing: 'Add malts to 9L of H20 at 74 °C. Mash for 60 minutes. Recirculate. Sparging. Collect 23 L of wort. Boil, add hops for 60 minutes.Cool wort, aerate, pitch yeast, ferment at 21 °C.', fermentation: 'Ferment started after 12 hours and lasted for 4 days.', tasting: 'Balanced hop bitterness with a strong malt backbone, floral hop aroma and a finish that is bitter without being harsh or astringent.'}),
    knex('beer').insert({name:'Better than Christmas', style: 'Irish Stout', brewer:'Rahmona Henry', yield:72, brewDate:'01 Dec 2015', bottlingDate:'30 Dec 2015', original: 1078, final: 1020, mash: 64, ferment: 20, abv: 6, ibu: 58, ingredients: 'Pale Malt, Biscuit Malt, Munich Malt, Chinook Hops, Centennial Hops', brewing: 'Add malts to 9L of H20 at 74 °C. Mash for 60 minutes. Recirculate. Sparging. Collect 23 L of wort. Boil, add hops for 60 minutes.Cool wort, aerate, pitch yeast, ferment at 21 °C.', fermentation: 'Ferment started after 12 hours and lasted for 4 days.', tasting: 'Balanced hop bitterness with a strong malt backbone, floral hop aroma and a finish that is bitter without being harsh or astringent.'}),
    knex('beer').insert({name:'Two Hours Twenty', style: 'Pilsner', brewer:'Rahmona Henry', yield:72, brewDate:'01 Dec 2015', bottlingDate:'30 Dec 2015', original: 1078, final: 1020, mash: 64, ferment: 20, abv: 6, ibu: 58, ingredients: 'Pale Malt, Biscuit Malt, Munich Malt, Chinook Hops, Centennial Hops', brewing: 'Add malts to 9L of H20 at 74 °C. Mash for 60 minutes. Recirculate. Sparging. Collect 23 L of wort. Boil, add hops for 60 minutes.Cool wort, aerate, pitch yeast, ferment at 21 °C.', fermentation: 'Ferment started after 12 hours and lasted for 4 days.', tasting: 'Balanced hop bitterness with a strong malt backbone, floral hop aroma and a finish that is bitter without being harsh or astringent.'}),
    knex('beer').insert({name:'The Chrysler', style: 'American IPA', brewer:'Rahmona Henry', yield:72, brewDate:'01 Dec 2015', bottlingDate:'30 Dec 2015', original: 1078, final: 1020, mash: 64, ferment: 20, abv: 6, ibu: 58, ingredients: 'Pale Malt, Biscuit Malt, Munich Malt, Chinook Hops, Centennial Hops', brewing: 'Add malts to 9L of H20 at 74 °C. Mash for 60 minutes. Recirculate. Sparging. Collect 23 L of wort. Boil, add hops for 60 minutes.Cool wort, aerate, pitch yeast, ferment at 21 °C.', fermentation: 'Ferment started after 12 hours and lasted for 4 days.', tasting: 'Balanced hop bitterness with a strong malt backbone, floral hop aroma and a finish that is bitter without being harsh or astringent.'})
)};
